### ISSUE TITLE
After fixing booklive issue, now it doesn't work anymore

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [vircoys/ccdl#6]
When starting the CcdlSimpleStarter.py file, it returns:
`Traceback (most recent call last):
  File "ccdlsimplestarter.py", line 9, in <module>
    from ccdl import (Binb2, ComicAction, ComicEarthstar, ComicLinkInfo,
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\[Me]\AppData\Roaming\Python\Python38\site-packages\ccdl-0.1.9.dev0-py3.8.egg\ccdl\__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\[Me]\AppData\Roaming\Python\Python38\site-packages\ccdl-0.1.9.dev0-py3.8.egg\ccdl\comic_action.py", line 8, in <module>
ModuleNotFoundError: No module named 'requests'`

**Comment by vircoys** [comment]
Maybe there is no requests package, try to execute the command "pip install -r requirements.txt" in the terminal.

**Comment by l-l-l-l-l-l** [comment]
Found the issue. I have both python 3.7 and 3.8 installed (3.8 didn't unistall 3.7), pip command updates just 3.7 but this version has decided to, somehow, run in 3.8.
Had to manually install all of the dependencies.
